export const PROFILE_NEW_USER = 'PROFILE_NEW_USER';
export const PROFILE_LOOKUP_COUNTRY_START = 'PROFILE_LOOKUP_COUNTRY_START';
export const PROFILE_LOOKUP_COUNTRY_FAILURE = 'PROFILE_LOOKUP_COUNTRY_FAILURE';
export const PROFILE_LOOKUP_COUNTRY_SUCCESS = 'PROFILE_LOOKUP_COUNTRY_SUCCESS';
export const PROFILE_RESET_USERNAME = 'PROFILE_RESET_USERNAME';

export const PLAY_SET_CONFIGS = 'PLAY_SET_CONFIGS';
export const PLAY_RESET_CONFIGS = 'PLAY_RESET_CONFIGS';

export const SESSION_FETCH_IMAGES_START = 'SESSION_FETCH_IMAGES_START';
export const SESSION_FETCH_IMAGES_SUCCESS = 'SESSION_FETCH_IMAGES_SUCCESS';
export const SESSION_FETCH_IMAGES_FAILURE = 'SESSION_FETCH_IMAGES_FAILURE';
export const SESSION_DUMP_IMAGES = 'SESSION_DUMP_IMAGES';
export const SESSION_UPDATE_CURRENT_CARDS = 'SESSION_UPDATE_CURRENT_CARDS';
export const SESSION_CHECK_PAIR = 'SESSION_CHECK_PAIR';
export const SESSION_CHECK_ENDGAME = 'SESSION_CHECK_ENDGAME';
export const SESSION_DO_ENDGAME = 'SESSION_DO_ENDGAME';
export const SESSION_RESET_GAME = 'SESSION_RESET_GAME';
export const SESSION_START_GAME = 'SESSION_START_GAME';
export const SESSION_COUNT_MOVES = 'SESSION_COUNT_MOVES';

export const HISTORY_FETCH_START = 'HISTORY_FETCH_START';
export const HISTORY_FETCH_SUCCESS = 'HISTORY_FETCH_SUCCESS';
export const HISTORY_FETCH_FAILURE = 'HISTORY_FETCH_FAILURE';
export const HISTORY_SAVE_START = 'HISTORY_SAVE_START';
export const HISTORY_SAVE_SUCCESS = 'HISTORY_SAVE_SUCCESS';
export const HISTORY_SAVE_FAILURE = 'HISTORY_SAVE_FAILURE';
export const HISTORY_RESET = 'HISTORY_RESET';
