export const PROFILE_NEW_USER = 'PROFILE_NEW_USER';
export const PROFILE_RESET_USERNAME = 'PROFILE_RESET_USERNAME';

export const PLAY_SET_CONFIGS = 'PLAY_SET_CONFIGS';
export const PLAY_RESET_CONFIGS = 'PLAY_RESET_CONFIGS';
export const SESSION_FETCH_IMAGES_START = 'SESSION_FETCH_IMAGES_START';
export const SESSION_FETCH_IMAGES_SUCCESS = 'SESSION_FETCH_IMAGES_SUCCESS';
export const SESSION_FETCH_IMAGES_FAILURE = 'SESSION_FETCH_IMAGES_FAILURE';
