export const PROFILE_NEW_USER = 'PROFILE_NEW_USER';
export const PROFILE_RESET_USERNAME = 'PROFILE_RESET_USERNAME';

export const PLAY_SET_CONFIGS = 'PLAY_SET_CONFIGS';
export const PLAY_RESET_CONFIGS = 'PLAY_RESET_CONFIGS';
export const PLAY_COUNT_MOVES = 'PLAY_COUNT_MOVES';

export const SESSION_FETCH_IMAGES_START = 'SESSION_FETCH_IMAGES_START';
export const SESSION_FETCH_IMAGES_SUCCESS = 'SESSION_FETCH_IMAGES_SUCCESS';
export const SESSION_FETCH_IMAGES_FAILURE = 'SESSION_FETCH_IMAGES_FAILURE';
export const SESSION_DUMP_IMAGES = 'SESSION_DUMP_IMAGES';
export const SESSION_UPDATE_CURRENT_CARDS = 'SESSION_UPDATE_CURRENT_CARDS';
export const SESSION_CHECK_PAIR = 'SESSION_CHECK_PAIR';
export const SESSION_CHECK_ENDGAME = 'SESSION_CHECK_ENDGAME';
